# Generated by Django 6.0.2 on 2026-02-19 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_count', models.IntegerField(default=0)),
                ('revenue_mean', models.FloatField(default=0.0)),
                ('revenue_m2', models.FloatField(default=0.0)),
                ('total_activities', models.IntegerField(default=0)),
                ('weighted_verification_sum', models.FloatField(default=0.0)),
                ('vsi_score', models.FloatField(default=0.0)),
                ('rsi_score', models.FloatField(default=0.0)),
                ('trust_score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
