# Generated by Django 6.0.2 on 2026-03-09 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=300)),
                ('activity_consistency', models.FloatField(default=0.0)),
                ('revenue_stability', models.FloatField(default=0.0)),
                ('verification_strength', models.FloatField(default=100.0)),
                ('repayment_behavior', models.FloatField(default=150.0)),
                ('growth_trend', models.FloatField(default=0.0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
