# Generated by Django 6.0.2 on 2026-02-19 12:45

import consent.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('SCORE_ONLY', 'Trust Score Only'), ('FULL_LEDGER', 'Full Financial Ledger'), ('IDENTITY_ONLY', 'Identity Verification Only')], default='SCORE_ONLY', max_length=20)),
                ('expires_at', models.DateTimeField(default=consent.models.default_expiration)),
                ('is_revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_consents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
