# Generated by Django 6.0.2 on 2026-02-18 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SALE', 'Sale'), ('HARVEST', 'Harvest'), ('EXPENSE', 'Expense'), ('LEDGER_SCAN', 'Ledger Scan')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('timestamp', models.DateTimeField()),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='evidence/%Y/%m/')),
                ('is_verified', models.BooleanField(default=False)),
                ('trust_score_impact', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
