# Generated by Django 6.0.2 on 2026-03-05 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('category', models.CharField(choices=[('SALES', 'Sales'), ('SERVICE_FEE', 'Service Fee'), ('OTHER_INCOME', 'Other Income'), ('INVENTORY', 'Inventory/Restock'), ('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('PAYROLL', 'Payroll'), ('MARKETING', 'Marketing'), ('TRANSPORT', 'Transport'), ('OTHER_EXPENSE', 'Other Expense')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'transaction_date'], name='ledger_tran_user_id_26c669_idx'), models.Index(fields=['transaction_type'], name='ledger_tran_transac_f447c2_idx')],
            },
        ),
    ]
